### ISSUE TITLE
NAME THE GAME

### ISSUE THREAD

**Issue by Kenoshen** [bitDecayGames/LudumDare48#20]
- Skinny Dipper
- Nudist Beach
- Holey Moley
- Save the Moley
- Lifeguard On Duty
- Snake in the Hole
- Mole in the Hole
- Mole On Duty
- Mole Of Duty
- Naked Mole Hill
- Broke Back Mole Hill
- Baywatch
- David Moleselhoff
- Moley Moley MOOOLEY
- Scrolly Moley
- The Deep Lifeguard
- Deep Dead Pool
- Deep Dive
- Sandy Lake
- Sandy Crack
- Deep Sand
- Dirt Down Deep

**Comment by jacque006** [comment]
- Rescue Rat
- Root Ranger
- Safety Mole
- Rat Race
- Danger Noodle Defuser
